.\" ============================================================================
.TH bio-solver 1 2008-11-02 "" "Biosensor modelling"
.SH NAME
bio-solver \- Biosensor modeller
.\" ============================================================================
.SH SYNOPSIS
.B bio-solver
.I model-file
.\" ============================================================================
.SH DESCRIPTION
.B bio-solver
performs simulations of the biosensor, specified in 
.IR model-file ,
which describes biosensor in XML format.
.\" ============================================================================
.SH AUTHOR
Karolis Petrauskas <k dot petrauskas at gmail dot com>
.\" ============================================================================
.SH "SEE ALSO"
.BR bio-editor (1)

