
CC=g++
CFLAGS=-c -I../src/libbiosensor

Cursor2DOpenBoundsTest:
	$(CC) $(CFLAGS) Cursor2DOpenBoundsTest.cxx
	$(CC) $(LDFLAGS) Cursor2DOpenBoundsTest.o -o Cursor2DOpenBoundsTest.tmp
	./Cursor2DOpenBoundsTest.tmp

