--- !ditz.rubyforge.org,2008-03-06/project 
name: kape1395.biosensor.solver-2D
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: kape1395.biosensor.solver-2D
releases: []

