#ifndef BIO_TRD_AmperometricInjectedElectrode2D_HXX
#define BIO_TRD_AmperometricInjectedElectrode2D_HXX
#include "../../biosensor.hxx"
#include "../slv/ISolver.hxx"
#include "../slv/ITransducer.hxx"
#include "../cfg/BoundAnalyzer.hxx"
#include "../dm/IDataModel.hxx"
#include "../dm/IGrid2D.hxx"
#include "../dm/ICursor2D.hxx"
#include "../dm/IComposite2D.hxx"
#include "../dm/ISegmentSplit.hxx"
#include <biosensor-xml.hxx>
#include <string>
#include <vector>
BIO_TRD_NS_BEGIN


/**
 *  Transducer: InjectedElectrode.
 */
class AmperometricInjectedElectrode2D : public BIO_SLV_NS::ITransducer
{
private:
    BIO_CFG_NS::StructureAnalyzer* structAnalyzer;
    BIO_DM_NS::IComposite2D* dataModel;
    BIO_XML_MODEL_NS::MediumName mediumName;
    BIO_XML_MODEL_NS::SubstanceName substanceName;
    int substanceIndex;

public:
    AmperometricInjectedElectrode2D(
        BIO_SLV_NS::ISolver* solver,
        BIO_XML_MODEL_NS::MediumName& mediumName,
        BIO_XML_MODEL_NS::SubstanceName& substanceName
    );

    virtual ~AmperometricInjectedElectrode2D();

    /**
     *  Returns current density, generated by the biosensor.
     */
    virtual double getOutput();

private:

};



BIO_TRD_NS_END
#endif
