#ifndef BIO_TRD_CompositeElectrode_HXX
#define BIO_TRD_CompositeElectrode_HXX
#include "../../biosensor.hxx"
#include "../slv/ISolver.hxx"
#include "../slv/ITransducer.hxx"
#include "../cfg/BoundAnalyzer.hxx"
#include "../dm/IDataModel.hxx"
#include "../dm/IGrid2D.hxx"
#include "../dm/ICursor2D.hxx"
#include "../dm/IComposite2D.hxx"
#include "../dm/ISegmentSplit.hxx"
#include "IntegralOverArea.hxx"
#include <biosensor-xml.hxx>
#include <string>
#include <vector>
BIO_TRD_NS_BEGIN


/**
 *  Transducer: InjectedElectrode.
 */
class CompositeElectrode : public BIO_SLV_NS::ITransducer
{
private:
    std::vector<BIO_SLV_NS::ITransducer *> transducers;
    std::vector<BIO_SLV_NS::ITransducer *> transducersToDelete;

public:
    CompositeElectrode();

    virtual ~CompositeElectrode();

    void addTransducer(BIO_SLV_NS::ITransducer* transducer, bool deleteOnDestruction);

    /**
     *  Returns current density, generated by the biosensor.
     */
    virtual double getOutput();

};



BIO_TRD_NS_END
#endif
