#! /usr/bin/env python
# -*- coding: iso-8859-1 -*-

import sys
import re

################################################################################
def error(message):
    sys.stderr.write('\nERROR: ' + message + '\n\n')
    sys.exit(1)


################################################################################
def output_halftime(file):
    sys.stdout.write('# A halftime of a steady state is calculated from: ' + file + '\n')
    inFile = open(file, 'r')

    #  Find last line.
    C_ss = 0.0
    lastLine = ''
    for inLine in inFile:
        if re.search('^#', inLine): continue
        C_ss = float(inLine.split('\t')[2])
        lastLine = inLine
    
    sys.stdout.write('# Assuming stedady state is: ' + re.compile('\t').sub(' ', lastLine))
    C_05 = C_ss / 2;

    #  Find halftime
    inFile.seek(0)
    for inLine in inFile:
        if re.search('^#', inLine): continue
        if C_05 <= float(inLine.split('\t')[2]):
            sys.stdout.write('# Time\tStep\tCurrentDensity\n')
            sys.stdout.write(inLine)
            break

    inFile.close()


################################################################################
def output_steady_state_current(file):
    sys.stdout.write('# A steady state current is calculated from: ' + file + '\n')
    inFile = open(file, 'r')

    lastLine = ''
    for inLine in inFile:
        if re.search('^#', inLine): continue
        lastLine = inLine

    sys.stdout.write('# Time\tStep\tCurrentDensity\n')
    sys.stdout.write(lastLine)
    
    inFile.close()


################################################################################
def output_concentration1d_by_index(file, direction, index):
    position = 0
    if 'horizontal'.startswith(direction.lower()) :
        direction = 'horizontal'
        position = 3
    elif 'vertical'.startswith(direction.lower()) :
        direction = 'vertical'
        position = 2
    else :
        error('Direction must be one of: h[orizontal], v[ertical]...')
    
    sys.stdout.write('# Concentrations by direction=' + direction + ' index=' + index + ' from: ' + file + '\n')
    inFile = open(file, 'r')

    fileHeader = True
    hp = re.compile('^#|^[\s]*$')
    for inLine in inFile:
            if hp.search(inLine) :
                if fileHeader :
                    sys.stdout.write(inLine)
            else :
                fileHeader = False
                if int(inLine.split('\t')[position]) == int(index) :
                    sys.stdout.write(inLine)
    inFile.close()


################################################################################


if len(sys.argv) < 2 :
    error("Command is required")

if sys.argv[1] == 'halftime' or sys.argv[1].startswith("ha") :
    if len(sys.argv) != 3: error('Please specify currentDensityVersusTime file')
    output_halftime(sys.argv[2])

elif sys.argv[1] == 'steadystate' or sys.argv[1].startswith("st") :
    if len(sys.argv) != 3: error('Please specify currentDensityVersusTime file')
    output_steady_state_current(sys.argv[2])

elif sys.argv[1] == 'concentration1d' :
    if len(sys.argv) != 5: error('Please specify direction, index and concentrations file')
    output_concentration1d_by_index(sys.argv[4], sys.argv[2], sys.argv[3])

elif sys.argv[1] == 'help' or sys.argv[1].startswith("he") :
    print '#'
    print '# usage: bio-output <subcommand> [arguments]'
    print '# Available subcommands are:'
    print '#     help'
    print '#     halftime <currentDensityFile>'
    print '#     steadystate <currentDensityFile>'
    print '#     concentration1d (h[orizontal]|v[ertical]) <idnex> <concentrationsFile>'
    print '#'

else:
    error('Unknown command, try "bio-output help"')

sys.exit(0)
