// Copyright (C) 2005-2007 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

/**
 * @file
 * @brief Generated from ModelReaction.xsd.
 */

#ifndef MODEL_REACTION_HXX
#define MODEL_REACTION_HXX

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/version.hxx>

#if (XSD_INT_VERSION != 3000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/tree/parsing.hxx>

#include <xsd/cxx/tree/serialization.hxx>
#include <xsd/cxx/xml/dom/serialization-header.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type type;
  typedef ::xsd::cxx::tree::simple_type<type> simple_type;

  // 8-bit
  //
  typedef signed char byte;
  typedef unsigned char unsigned_byte;

  // 16-bit
  //
  typedef short short_;
  typedef unsigned short unsigned_short;

  // 32-bit
  //
  typedef int int_;
  typedef unsigned int unsigned_int;

  // 64-bit
  //
  typedef long long long_;
  typedef unsigned long long unsigned_long;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long integer;
  typedef integer non_positive_integer;
  typedef integer non_negative_integer;
  typedef integer positive_integer;
  typedef integer negative_integer;

  // Boolean.
  //
  typedef bool boolean;

  // Floating-point types.
  //
  typedef float float_;
  typedef double double_;
  typedef double decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< char, simple_type > string;
  typedef ::xsd::cxx::tree::normalized_string< char, string > normalized_string;
  typedef ::xsd::cxx::tree::token< char, normalized_string > token;
  typedef ::xsd::cxx::tree::name< char, token > name;
  typedef ::xsd::cxx::tree::nmtoken< char, token > nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< char, simple_type, nmtoken> nmtokens;
  typedef ::xsd::cxx::tree::ncname< char, name > ncname;
  typedef ::xsd::cxx::tree::language< char, token > language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< char, ncname > id;
  typedef ::xsd::cxx::tree::idref< type, char, ncname > idref;
  typedef ::xsd::cxx::tree::idrefs< char, simple_type, idref > idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< char, simple_type > uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< char, simple_type, uri, ncname > qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< char > buffer;
  typedef ::xsd::cxx::tree::base64_binary< char, simple_type > base64_binary;
  typedef ::xsd::cxx::tree::hex_binary< char, simple_type > hex_binary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::date< char, simple_type > date;
  typedef ::xsd::cxx::tree::date_time< char, simple_type > date_time;
  typedef ::xsd::cxx::tree::duration< char, simple_type > duration;
  typedef ::xsd::cxx::tree::day< char, simple_type > day;
  typedef ::xsd::cxx::tree::month< char, simple_type > month;
  typedef ::xsd::cxx::tree::month_day< char, simple_type > month_day;
  typedef ::xsd::cxx::tree::year< char, simple_type > year;
  typedef ::xsd::cxx::tree::year_month< char, simple_type > year_month;
  typedef ::xsd::cxx::tree::time< char, simple_type > time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< char, ncname > entity;
  typedef ::xsd::cxx::tree::entities< char, simple_type, entity > entities;

  // Namespace information. Used in serialization functions.
  //
  typedef ::xsd::cxx::xml::dom::namespace_info < char > namespace_info;
  typedef ::xsd::cxx::xml::dom::namespace_infomap < char > namespace_infomap;

  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags flags;
  typedef ::xsd::cxx::tree::properties< char > properties;

  // DOM user data key for back pointers to tree nodes.
  //
#ifndef XSD_CXX_TREE_TREE_NODE_KEY_IN___XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY_IN___XML_SCHEMA

  const XMLCh* const tree_node_key = ::xsd::cxx::tree::user_data_keys::node;

#endif

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< char > exception;
  typedef ::xsd::cxx::tree::parsing< char > parsing;
  typedef ::xsd::cxx::tree::expected_element< char > expected_element;
  typedef ::xsd::cxx::tree::unexpected_element< char > unexpected_element;
  typedef ::xsd::cxx::tree::expected_attribute< char > expected_attribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > unexpected_enumerator;
  typedef ::xsd::cxx::tree::expected_text_content< char > expected_text_content;
  typedef ::xsd::cxx::tree::no_type_info< char > no_type_info;
  typedef ::xsd::cxx::tree::not_derived< char > not_derived;
  typedef ::xsd::cxx::tree::duplicate_id< char > duplicate_id;
  typedef ::xsd::cxx::tree::serialization< char > serialization;
  typedef ::xsd::cxx::tree::no_namespace_mapping< char > no_namespace_mapping;
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > no_prefix_mapping;
  typedef ::xsd::cxx::tree::xsi_already_in_use< char > xsi_already_in_use;
  typedef ::xsd::cxx::tree::bounds< char > bounds;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity severity;
  typedef ::xsd::cxx::tree::error< char > error;
  typedef ::xsd::cxx::tree::diagnostics< char > diagnostics;

  // Error handler interface.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;
}

// Forward declarations.
//
namespace bio
{
  namespace xml
  {
    namespace model
    {
      namespace reaction
      {
        class MichaelisMenten;
        class ReductionOxidation;
        class ReductionOxidationElement;
      }
    }
  }
}


#include <memory>    // std::auto_ptr
#include <algorithm> // std::binary_search

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "Model.hxx"

namespace bio
{
  namespace xml
  {
    namespace model
    {
      /**
       * @brief C++ namespace for the %http://lt.5grupe.karolis/biosensor/model/reaction
       * schema namespace.
       */
      namespace reaction
      {
        /**
         * @brief Class corresponding to the %MichaelisMenten schema type.
         *
         * @nosubgrouping
         */
        class MichaelisMenten: public ::bio::xml::model::MediumReaction
        {
          public:
          /**
           * @name substrate
           *
           * @brief Accessor and modifier functions for the %substrate
           * required attribute.
           */
          //@{

          /**
           * @brief Attribute type.
           */
          typedef ::bio::xml::model::SubstanceName substrate_type;

          /**
           * @brief Attribute traits type.
           */
          typedef ::xsd::cxx::tree::traits< substrate_type, char > substrate_traits;

          /**
           * @brief Return a read-only (constant) reference to the attribute.
           *
           * @return A constant reference to the attribute.
           */
          const substrate_type&
          substrate () const;

          /**
           * @brief Return a read-write reference to the attribute.
           *
           * @return A reference to the attribute.
           */
          substrate_type&
          substrate ();

          /**
           * @brief Set the attribute value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the attribute.
           */
          void
          substrate (const substrate_type& x);

          /**
           * @brief Set the attribute value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly instead
           * of making a copy.
           */
          void
          substrate (::std::auto_ptr< substrate_type > p);

          //@}

          /**
           * @name product
           *
           * @brief Accessor and modifier functions for the %product
           * required attribute.
           */
          //@{

          /**
           * @brief Attribute type.
           */
          typedef ::bio::xml::model::SubstanceName product_type;

          /**
           * @brief Attribute traits type.
           */
          typedef ::xsd::cxx::tree::traits< product_type, char > product_traits;

          /**
           * @brief Return a read-only (constant) reference to the attribute.
           *
           * @return A constant reference to the attribute.
           */
          const product_type&
          product () const;

          /**
           * @brief Return a read-write reference to the attribute.
           *
           * @return A reference to the attribute.
           */
          product_type&
          product ();

          /**
           * @brief Set the attribute value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the attribute.
           */
          void
          product (const product_type& x);

          /**
           * @brief Set the attribute value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly instead
           * of making a copy.
           */
          void
          product (::std::auto_ptr< product_type > p);

          //@}

          /**
           * @name V_max
           *
           * @brief Accessor and modifier functions for the %V_max
           * required attribute.
           */
          //@{

          /**
           * @brief Attribute type.
           */
          typedef ::bio::xml::model::SymbolName V_max_type;

          /**
           * @brief Attribute traits type.
           */
          typedef ::xsd::cxx::tree::traits< V_max_type, char > V_max_traits;

          /**
           * @brief Return a read-only (constant) reference to the attribute.
           *
           * @return A constant reference to the attribute.
           */
          const V_max_type&
          V_max () const;

          /**
           * @brief Return a read-write reference to the attribute.
           *
           * @return A reference to the attribute.
           */
          V_max_type&
          V_max ();

          /**
           * @brief Set the attribute value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the attribute.
           */
          void
          V_max (const V_max_type& x);

          /**
           * @brief Set the attribute value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly instead
           * of making a copy.
           */
          void
          V_max (::std::auto_ptr< V_max_type > p);

          //@}

          /**
           * @name K_M
           *
           * @brief Accessor and modifier functions for the %K_M
           * required attribute.
           */
          //@{

          /**
           * @brief Attribute type.
           */
          typedef ::bio::xml::model::SymbolName K_M_type;

          /**
           * @brief Attribute traits type.
           */
          typedef ::xsd::cxx::tree::traits< K_M_type, char > K_M_traits;

          /**
           * @brief Return a read-only (constant) reference to the attribute.
           *
           * @return A constant reference to the attribute.
           */
          const K_M_type&
          K_M () const;

          /**
           * @brief Return a read-write reference to the attribute.
           *
           * @return A reference to the attribute.
           */
          K_M_type&
          K_M ();

          /**
           * @brief Set the attribute value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the attribute.
           */
          void
          K_M (const K_M_type& x);

          /**
           * @brief Set the attribute value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly instead
           * of making a copy.
           */
          void
          K_M (::std::auto_ptr< K_M_type > p);

          //@}

          /**
           * @name Constructors
           */
          //@{

          /**
           * @brief Construct an instance from the ultimate base and
           * initializers for required elements and attributes.
           */
          MichaelisMenten (const substrate_type&,
                           const product_type&,
                           const V_max_type&,
                           const K_M_type&);

          /**
           * @brief Construct an instance from a DOM element.
           *
           * @param e A DOM element to extract the data from.
           * @param f Flags to construct the new instance with.
           * @param c A pointer to the object that will contain the new
           * instance.
           */
          MichaelisMenten (const ::xercesc::DOMElement& e,
                           ::xml_schema::flags f = 0,
                           ::xml_schema::type* c = 0);

          /**
           * @brief Copy constructor.
           *
           * @param x An instance to make a copy of.
           * @param f Flags to construct the copy with.
           * @param c A pointer to the object that will contain the copy.
           *
           * For polymorphic object models use the _clone function instead.
           */
          MichaelisMenten (const MichaelisMenten& x,
                           ::xml_schema::flags f = 0,
                           ::xml_schema::type* c = 0);

          /**
           * @brief Copy the object polymorphically.
           *
           * @param f Flags to construct the copy with.
           * @param c A pointer to the object that will contain the copy.
           * @return A pointer to the dynamically allocated copy.
           *
           * This function ensures that the dynamic type of an instance is
           * used for copying and should be used for polymorphic object
           * models instead of the copy constructor.
           */
          virtual MichaelisMenten*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::type* c = 0) const;

          //@}

          // Implementation.
          //
          protected:
          void
          parse (::xsd::cxx::xml::dom::parser< char >&,
                 ::xml_schema::flags);

          private:
          ::xsd::cxx::tree::one< substrate_type > substrate_;
          ::xsd::cxx::tree::one< product_type > product_;
          ::xsd::cxx::tree::one< V_max_type > V_max_;
          ::xsd::cxx::tree::one< K_M_type > K_M_;
        };

        /**
         * @brief Class corresponding to the %ReductionOxidation schema type.
         *
         * @nosubgrouping
         */
        class ReductionOxidation: public ::bio::xml::model::MediumReaction
        {
          public:
          /**
           * @name substrate
           *
           * @brief Accessor and modifier functions for the %substrate
           * sequence element.
           */
          //@{

          /**
           * @brief Element type.
           */
          typedef ::bio::xml::model::reaction::ReductionOxidationElement substrate_type;

          /**
           * @brief Element sequence container type.
           */
          typedef ::xsd::cxx::tree::sequence< substrate_type > substrate_sequence;

          /**
           * @brief Element iterator type.
           */
          typedef substrate_sequence::iterator substrate_iterator;

          /**
           * @brief Element constant iterator type.
           */
          typedef substrate_sequence::const_iterator substrate_const_iterator;

          /**
           * @brief Element traits type.
           */
          typedef ::xsd::cxx::tree::traits< substrate_type, char > substrate_traits;

          /**
           * @brief Return a read-only (constant) reference to the element
           * sequence.
           *
           * @return A constant reference to the sequence container.
           */
          const substrate_sequence&
          substrate () const;

          /**
           * @brief Return a read-write reference to the element sequence.
           *
           * @return A reference to the sequence container.
           */
          substrate_sequence&
          substrate ();

          /**
           * @brief Copy elements from a given sequence.
           *
           * @param s A sequence to copy elements from.
           *
           * For each element in @a s this function makes a copy and adds it 
           * to the sequence. Note that this operation completely changes the 
           * sequence and all old elements will be lost.
           */
          void
          substrate (const substrate_sequence& s);

          //@}

          /**
           * @name product
           *
           * @brief Accessor and modifier functions for the %product
           * sequence element.
           */
          //@{

          /**
           * @brief Element type.
           */
          typedef ::bio::xml::model::reaction::ReductionOxidationElement product_type;

          /**
           * @brief Element sequence container type.
           */
          typedef ::xsd::cxx::tree::sequence< product_type > product_sequence;

          /**
           * @brief Element iterator type.
           */
          typedef product_sequence::iterator product_iterator;

          /**
           * @brief Element constant iterator type.
           */
          typedef product_sequence::const_iterator product_const_iterator;

          /**
           * @brief Element traits type.
           */
          typedef ::xsd::cxx::tree::traits< product_type, char > product_traits;

          /**
           * @brief Return a read-only (constant) reference to the element
           * sequence.
           *
           * @return A constant reference to the sequence container.
           */
          const product_sequence&
          product () const;

          /**
           * @brief Return a read-write reference to the element sequence.
           *
           * @return A reference to the sequence container.
           */
          product_sequence&
          product ();

          /**
           * @brief Copy elements from a given sequence.
           *
           * @param s A sequence to copy elements from.
           *
           * For each element in @a s this function makes a copy and adds it 
           * to the sequence. Note that this operation completely changes the 
           * sequence and all old elements will be lost.
           */
          void
          product (const product_sequence& s);

          //@}

          /**
           * @name rate
           *
           * @brief Accessor and modifier functions for the %rate
           * required attribute.
           */
          //@{

          /**
           * @brief Attribute type.
           */
          typedef ::bio::xml::model::SymbolName rate_type;

          /**
           * @brief Attribute traits type.
           */
          typedef ::xsd::cxx::tree::traits< rate_type, char > rate_traits;

          /**
           * @brief Return a read-only (constant) reference to the attribute.
           *
           * @return A constant reference to the attribute.
           */
          const rate_type&
          rate () const;

          /**
           * @brief Return a read-write reference to the attribute.
           *
           * @return A reference to the attribute.
           */
          rate_type&
          rate ();

          /**
           * @brief Set the attribute value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the attribute.
           */
          void
          rate (const rate_type& x);

          /**
           * @brief Set the attribute value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly instead
           * of making a copy.
           */
          void
          rate (::std::auto_ptr< rate_type > p);

          //@}

          /**
           * @name Constructors
           */
          //@{

          /**
           * @brief Construct an instance from the ultimate base and
           * initializers for required elements and attributes.
           */
          ReductionOxidation (const rate_type&);

          /**
           * @brief Construct an instance from a DOM element.
           *
           * @param e A DOM element to extract the data from.
           * @param f Flags to construct the new instance with.
           * @param c A pointer to the object that will contain the new
           * instance.
           */
          ReductionOxidation (const ::xercesc::DOMElement& e,
                              ::xml_schema::flags f = 0,
                              ::xml_schema::type* c = 0);

          /**
           * @brief Copy constructor.
           *
           * @param x An instance to make a copy of.
           * @param f Flags to construct the copy with.
           * @param c A pointer to the object that will contain the copy.
           *
           * For polymorphic object models use the _clone function instead.
           */
          ReductionOxidation (const ReductionOxidation& x,
                              ::xml_schema::flags f = 0,
                              ::xml_schema::type* c = 0);

          /**
           * @brief Copy the object polymorphically.
           *
           * @param f Flags to construct the copy with.
           * @param c A pointer to the object that will contain the copy.
           * @return A pointer to the dynamically allocated copy.
           *
           * This function ensures that the dynamic type of an instance is
           * used for copying and should be used for polymorphic object
           * models instead of the copy constructor.
           */
          virtual ReductionOxidation*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::type* c = 0) const;

          //@}

          // Implementation.
          //
          protected:
          void
          parse (::xsd::cxx::xml::dom::parser< char >&,
                 ::xml_schema::flags);

          private:
          substrate_sequence substrate_;
          product_sequence product_;
          ::xsd::cxx::tree::one< rate_type > rate_;
        };

        /**
         * @brief Class corresponding to the %ReductionOxidationElement schema type.
         *
         * @nosubgrouping
         */
        class ReductionOxidationElement: public ::xml_schema::type
        {
          public:
          /**
           * @name name
           *
           * @brief Accessor and modifier functions for the %name
           * required attribute.
           */
          //@{

          /**
           * @brief Attribute type.
           */
          typedef ::bio::xml::model::SubstanceName name_type;

          /**
           * @brief Attribute traits type.
           */
          typedef ::xsd::cxx::tree::traits< name_type, char > name_traits;

          /**
           * @brief Return a read-only (constant) reference to the attribute.
           *
           * @return A constant reference to the attribute.
           */
          const name_type&
          name () const;

          /**
           * @brief Return a read-write reference to the attribute.
           *
           * @return A reference to the attribute.
           */
          name_type&
          name ();

          /**
           * @brief Set the attribute value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the attribute.
           */
          void
          name (const name_type& x);

          /**
           * @brief Set the attribute value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly instead
           * of making a copy.
           */
          void
          name (::std::auto_ptr< name_type > p);

          //@}

          /**
           * @name coefficient
           *
           * @brief Accessor and modifier functions for the %coefficient
           * optional attribute with a default value.
           */
          //@{

          /**
           * @brief Attribute type.
           */
          typedef ::xml_schema::integer coefficient_type;

          /**
           * @brief Attribute traits type.
           */
          typedef ::xsd::cxx::tree::traits< coefficient_type, char > coefficient_traits;

          /**
           * @brief Return a read-only (constant) reference to the attribute.
           *
           * @return A constant reference to the attribute.
           */
          const coefficient_type&
          coefficient () const;

          /**
           * @brief Return a read-write reference to the attribute.
           *
           * @return A reference to the attribute.
           */
          coefficient_type&
          coefficient ();

          /**
           * @brief Set the attribute value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the attribute.
           */
          void
          coefficient (const coefficient_type& x);

          /**
           * @brief Return the default value for the attribute.
           *
           * @return A read-only (constant) reference to the attribute's
           * default value.
           */
          static const coefficient_type&
          coefficient_default_value ();

          //@}

          /**
           * @name Constructors
           */
          //@{

          /**
           * @brief Construct an instance from the ultimate base and
           * initializers for required elements and attributes.
           */
          ReductionOxidationElement (const name_type&);

          /**
           * @brief Construct an instance from a DOM element.
           *
           * @param e A DOM element to extract the data from.
           * @param f Flags to construct the new instance with.
           * @param c A pointer to the object that will contain the new
           * instance.
           */
          ReductionOxidationElement (const ::xercesc::DOMElement& e,
                                     ::xml_schema::flags f = 0,
                                     ::xml_schema::type* c = 0);

          /**
           * @brief Copy constructor.
           *
           * @param x An instance to make a copy of.
           * @param f Flags to construct the copy with.
           * @param c A pointer to the object that will contain the copy.
           *
           * For polymorphic object models use the _clone function instead.
           */
          ReductionOxidationElement (const ReductionOxidationElement& x,
                                     ::xml_schema::flags f = 0,
                                     ::xml_schema::type* c = 0);

          /**
           * @brief Copy the object polymorphically.
           *
           * @param f Flags to construct the copy with.
           * @param c A pointer to the object that will contain the copy.
           * @return A pointer to the dynamically allocated copy.
           *
           * This function ensures that the dynamic type of an instance is
           * used for copying and should be used for polymorphic object
           * models instead of the copy constructor.
           */
          virtual ReductionOxidationElement*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::type* c = 0) const;

          //@}

          // Implementation.
          //
          protected:
          void
          parse (::xsd::cxx::xml::dom::parser< char >&,
                 ::xml_schema::flags);

          private:
          ::xsd::cxx::tree::one< name_type > name_;
          ::xsd::cxx::tree::one< coefficient_type > coefficient_;
          static const coefficient_type coefficient_default_value_;
        };
      }
    }
  }
}

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMInputSource.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace bio
{
  namespace xml
  {
    namespace model
    {
      namespace reaction
      {
      }
    }
  }
}

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/framework/XMLFormatter.hpp>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

namespace bio
{
  namespace xml
  {
    namespace model
    {
      namespace reaction
      {
        void
        operator<< (::xercesc::DOMElement&, const MichaelisMenten&);

        void
        operator<< (::xercesc::DOMElement&, const ReductionOxidation&);

        void
        operator<< (::xercesc::DOMElement&, const ReductionOxidationElement&);
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // MODEL_REACTION_HXX
